services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: gestor_de_turnos
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/init_mysql.sql:/docker-entrypoint-initdb.d/init_mysql.sql

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - backend/.env
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: gestor_de_turnos
      DB_USER: root
      DB_PASSWORD: root
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    environment:
      BACKEND_URL: http://backend:5000
    ports:
      - "5001:5001"
    depends_on:
      - backend

volumes:
  mysql_data:
